version: "3.8"

services:
  # Redis standalone
  redis:
    image: redis:7.2-alpine
    container_name: ems-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - ems-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Commander (Web UI for Redis)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ems-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin123
    depends_on:
      - redis
    networks:
      - ems-network

  # Redis Cluster (optional - for production)
  redis-cluster-node-1:
    image: redis:7.2-alpine
    container_name: ems-redis-cluster-1
    restart: unless-stopped
    ports:
      - "7001:7001"
    volumes:
      - redis_cluster_1:/data
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - ems-network
    profiles:
      - cluster

  redis-cluster-node-2:
    image: redis:7.2-alpine
    container_name: ems-redis-cluster-2
    restart: unless-stopped
    ports:
      - "7002:7002"
    volumes:
      - redis_cluster_2:/data
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - ems-network
    profiles:
      - cluster

  redis-cluster-node-3:
    image: redis:7.2-alpine
    container_name: ems-redis-cluster-3
    restart: unless-stopped
    ports:
      - "7003:7003"
    volumes:
      - redis_cluster_3:/data
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - ems-network
    profiles:
      - cluster

  # Redis Sentinel (optional - for high availability)
  redis-sentinel-1:
    image: redis:7.2-alpine
    container_name: ems-redis-sentinel-1
    restart: unless-stopped
    ports:
      - "26379:26379"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis
    networks:
      - ems-network
    profiles:
      - sentinel

  redis-sentinel-2:
    image: redis:7.2-alpine
    container_name: ems-redis-sentinel-2
    restart: unless-stopped
    ports:
      - "26380:26379"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis
    networks:
      - ems-network
    profiles:
      - sentinel

  redis-sentinel-3:
    image: redis:7.2-alpine
    container_name: ems-redis-sentinel-3
    restart: unless-stopped
    ports:
      - "26381:26379"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis
    networks:
      - ems-network
    profiles:
      - sentinel

volumes:
  redis_data:
    driver: local
  redis_cluster_1:
    driver: local
  redis_cluster_2:
    driver: local
  redis_cluster_3:
    driver: local

networks:
  ems-network:
    driver: bridge
    name: ems-network
