import { config } from "dotenv";
config({ path: ".env" });

const {
  DB_NAME,
  DB_USERNAME,
  DB_PASSWORD,
  DB_HOST,
  DB_PORT,
  DB_DIALECT,
  NODE_ENV,
  FRONT_END_URL,
  S3_URL,
  AWS_ACCESS_KEY,
  AWS_SECRET,
  AWS_BUCKET_NAME,
  BREVO_SMTP_SERVER,
  BREVO_PORT,
  BREVO_LOGIN,
  BREVO_USER,
  BREVO_PASSWORD,
}: any = process.env;

export default {
  DB_NAME,
  DB_USERNAME,
  DB_PASSWORD,
  DB_HOST,
  DB_PORT,
  DB_DIALECT,
  NODE_ENV,
  FRONT_END_URL,
  S3_URL,
  AWS_ACCESS_KEY,
  AWS_SECRET,
  AWS_BUCKET_NAME,
  BREVO_SMTP_SERVER,
  BREVO_PORT,
  BREVO_LOGIN,
  BREVO_USER,
  BREVO_PASSWORD,
};
