import { master_departments } from "@prisma/client";

export const masterDepartments: {
  table: string;
  data: master_departments[];
} = {
  table: "master_departments",
  data: [
    {
      id: 1,
      name: "Human Resources",
      description:
        "Manages recruitment, employee relations, and company policies",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 2,
      name: "Finance",
      description: "Handles budgeting, accounting, and financial planning",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 3,
      name: "Marketing",
      description: "Develops marketing strategies and branding initiatives",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 4,
      name: "Sales",
      description: "Manages client relationships and revenue generation",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 5,
      name: "Information Technology (IT)",
      description: "Manages company technology, networks, and cybersecurity",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 6,
      name: "Product Management",
      description: "Oversees product development and lifecycle",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 7,
      name: "Operations",
      description: "Ensures smooth business processes and logistics",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 8,
      name: "Customer Support",
      description: "Provides assistance and resolves customer inquiries",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 9,
      name: "Legal",
      description: "Handles compliance, contracts, and legal matters",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 10,
      name: "Research and Development (R&D)",
      description: "Focuses on innovation and new product development",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 11,
      name: "Manufacturing",
      description: "Oversees production, quality control, and supply chain",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 12,
      name: "Quality Assurance",
      description: "Ensures product and service quality standards",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 13,
      name: "Procurement",
      description: "Manages purchasing and vendor relationships",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 14,
      name: "Logistics & Supply Chain",
      description: "Coordinates the movement of goods and inventory",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 15,
      name: "Medical & Healthcare",
      description: "Provides healthcare services, research, and treatment",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 16,
      name: "Education & Training",
      description: "Focuses on employee training and skill development",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 17,
      name: "Security",
      description: "Ensures workplace safety and data security",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 18,
      name: "Public Relations",
      description: "Handles media relations and corporate communications",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 19,
      name: "Facility Management",
      description: "Manages office spaces, maintenance, and infrastructure",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 20,
      name: "Corporate Strategy",
      description: "Defines business strategies and competitive positioning",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 21,
      name: "Networking & Infrastructure",
      description: "Manages servers, routers, switches, and network systems",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 22,
      name: "Transport & Fleet Management",
      description: "Handles company vehicles and transportation services",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 23,
      name: "Maintenance",
      description: "Responsible for repair, upkeep, and workplace utilities",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 24,
      name: "IT Administration",
      description:
        "Manages IT hardware, software licensing, and end-user support",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ],
};
