import { master_designations } from "@prisma/client";

export const masterDesignations: {
  table: string;
  data: master_designations[];
} = {
  table: "master_designations",
  data: [
    {
      id: 1,
      name: "Chief Executive Officer (CEO)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 2,
      name: "Chief Operating Officer (COO)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 3,
      name: "Chief Financial Officer (CFO)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 4,
      name: "Chief Technology Officer (CTO)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 5,
      name: "Chief Marketing Officer (CMO)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 6,
      name: "Chief Human Resources Officer (CHRO)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 7,
      name: "Chief Information Officer (CIO)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 8,
      name: "Chief Data Officer (CDO)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 9,
      name: "Chief Product Officer (CPO)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 10,
      name: "Chief Legal Officer (CLO)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 11,
      name: "Chief Compliance Officer (CCO)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 12,
      name: "Chief Supply Chain Officer (CSO)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 13,
      name: "Software Engineer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 14,
      name: "Senior Software Engineer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 15,
      name: "Full Stack Developer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 16,
      name: "Frontend Developer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 17,
      name: "Backend Developer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 18,
      name: "Mobile App Developer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 19,
      name: "Cloud Engineer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 20,
      name: "DevOps Engineer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 21,
      name: "Data Scientist",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 22,
      name: "Data Analyst",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 23,
      name: "AI/ML Engineer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 24,
      name: "Cybersecurity Analyst",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 25,
      name: "Network Administrator",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 26,
      name: "IT Support Specialist",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 27,
      name: "QA Engineer / Test Engineer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 28,
      name: "Product Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 29,
      name: "UI/UX Designer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 30,
      name: "Sales Executive",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 31,
      name: "Sales Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 32,
      name: "Business Development Executive",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 33,
      name: "Business Development Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 34,
      name: "Account Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 35,
      name: "Digital Marketing Executive",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 36,
      name: "Digital Marketing Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 37,
      name: "SEO Specialist",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 38,
      name: "Content Writer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 39,
      name: "Social Media Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 40,
      name: "Brand Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 41,
      name: "Market Research Analyst",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 42,
      name: "Public Relations Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 43,
      name: "Customer Success Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 44,
      name: "Financial Analyst",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 45,
      name: "Accountant",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 46,
      name: "Chartered Accountant (CA)",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 47,
      name: "Cost Accountant",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 48,
      name: "Investment Analyst",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 49,
      name: "Risk Analyst",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 50,
      name: "Auditor",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 51,
      name: "Tax Consultant",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 52,
      name: "Finance Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 53,
      name: "HR Executive",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 54,
      name: "HR Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 55,
      name: "Recruitment Specialist",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 56,
      name: "Payroll Specialist",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 57,
      name: "Training & Development Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 58,
      name: "Office Administrator",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 59,
      name: "Administrative Assistant",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 60,
      name: "Operations Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 61,
      name: "Logistics Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 62,
      name: "Supply Chain Analyst",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 63,
      name: "Procurement Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 64,
      name: "Inventory Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 65,
      name: "Warehouse Supervisor",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 66,
      name: "Legal Advisor",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 67,
      name: "Compliance Officer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 68,
      name: "Corporate Lawyer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 69,
      name: "Contract Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 70,
      name: "Doctor",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 71,
      name: "Surgeon",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 72,
      name: "Nurse",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 73,
      name: "Medical Officer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 74,
      name: "Pharmacist",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 75,
      name: "Lab Technician",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 76,
      name: "Teacher",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 77,
      name: "Lecturer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 78,
      name: "Professor",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 79,
      name: "Trainer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 80,
      name: "Instructional Designer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 81,
      name: "Customer Service Executive",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 82,
      name: "Technical Support Engineer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 83,
      name: "Call Center Representative",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 84,
      name: "Mechanical Engineer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 85,
      name: "Civil Engineer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 86,
      name: "Electrical Engineer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 87,
      name: "Industrial Engineer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 88,
      name: "Production Manager",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 89,
      name: "Graphic Designer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 90,
      name: "Video Editor",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 91,
      name: "Photographer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 92,
      name: "Journalist",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 93,
      name: "Web Designer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 94,
      name: "Web Developer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 95,
      name: "Mobile App Designer",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 96,
      name: "Database Administrator",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 97,
      name: "Juniour Executive",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 98,
      name: "Senior Executive",
      description: "",
      is_active: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ],
};
